language: php
php:
  - 7.3
script:
  - npm install
  - composer install
  - npm run build
  - ./travis.sh
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
    secure: "D2yHLUgkSaq+1L+HY8BbldN01avSAiOQ6wGdWzJF50kpttCNcWQIOHgCcJOFvrZKOvIRJiZ+kcGQSBKfCbUp8H/Uct9cpKwkf6ciR5xhjNGWu7fZKQNrVhIHoKp/CRMYk1aEnIJ7UEPF6Bgr+J80xbC7GxlM5GVQSkH1hjBZ15Zb25vFNDC16EYwUdo5bhLIUbyp8DwCJfKaPSqunkMf/YND8RlDSUV7WGhmpa8zPpB3f2Ksgo3yoZxcFcrmbJTc9HIH0uGupADXpq/qvkmDdi8UdI6jtQBpnbqN7fcdCkigB7VVk7WCbj2zCRts+Qf1r+VtC2gLPrcUinIY5UeegNDgHJzwDPMnQDKo+6ePwDgGCe1Gm9XCqY6R5J4SDHADAQYVj8NBu+V8NQ6Qaoe1jpJUyIiwWW/ldX7wtSr8fqxdVFADZynvjwAQP+FcU5m7wlGV5FfBUgQF3m1mluwYp+XBCN8BRIP/76XHN/MJTtFqhrrgUCdnaxDxHYq6V6o2D391tE4iUqinjaMrv7wD+eUL8FkhWY5dP9NblyTlBER3oxtzCAbt82j6PefhAIZ3ZHb6EAxhOUM++ms3Sm2Cz4tdqOmj7qoA2gaR24QhrhAymCxO4pElR4NowZct3sTefT95opjxpDj6DyVV9Kmsuq3qrFrFW/0YJIjGW13A3oE="
